# name: Matrix Configuration

# on: 
#   push:
#   workflow_dispatch:
    
# jobs:
#     deploy:
#         strategy:
#           fail-fast: false
#           max-parallel: 2
#           matrix:
#             os: [ubuntu-latest, ubuntu-20.04, windows-latest]
#             images: [hello-world, alpine]
#             exclude:
#               - images: alpine
#                 os: windows-latest
#               - images: hello-world
#                 os: windows-latest
#             include:
#               - images: amd64/alpine
#                 os: ubuntu-20.04
#         runs-on: ${{ matrix.os }}
#         steps:
#         - name: Echo Docker Details
#           run: docker info

#         - name: Run Images on ${{ matrix.os }}
#           run: docker run ${{matrix.images}}


name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: hello-world
          - os: windows-latest
            images: alpine
        include:
          - os: ubuntu-20.04
            images: amd64/alpine

    runs-on: ${{ matrix.os }}

    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Docker Image
        run: docker run ${{ matrix.images }}
